apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "konga.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "konga.name" . }}
    helm.sh/chart: {{ include "konga.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- if .Values.config.port }}
  PORT: {{ .Values.config.port | quote }}
  {{- end }}
  {{- if .Values.config.node_env }}
  NODE_ENV: {{ .Values.config.node_env }}
  {{- end }}
  {{- if .Values.config.ssl.enabled }}
  SSL_KEY_PATH: {{ .Values.config.ssl.key_path }}
  SSL_CRT_PATH: {{ .Values.config.ssl.crt_path }}
  {{- end }}
  {{- if .Values.config.konga_hook_timeout }}
  KONGA_HOOK_TIMEOUT: {{ .Values.config.konga_hook_timeout | quote }}
  {{- end }}
  {{- if .Values.config.log_level }}
  KONGA_LOG_LEVEL: {{ .Values.config.log_level }}
  {{- end }}
  {{- if .Values.config.token_secret }}
  TOKEN_SECRET: {{ .Values.config.token_secret }}
  {{- end }}
  {{- if .Values.ingress.enabled }}
  BASE_URL: {{ .Values.ingress.hostname }}
  {{- end }}
  NODE_TLS_REJECT_UNAUTHORIZED: "0"

  {{- if .Values.database.enabled }}
  DB_ADAPTER: {{ .Values.database.adapter }}
  {{- if .Values.database.uri }}
  DB_URI: {{ .Values.database.uri }}
  {{- end }}
  DB_HOST: {{ .Values.database.host }}
  DB_PORT: {{ .Values.database.port | quote }}
  {{- if not .Values.database.credentials.from_secret }}
  DB_USER: {{ .Values.database.credentials.username }}
  DB_PASSWORD: {{ .Values.database.credentials.password }}
  {{- end }}
  DB_DATABASE: {{ .Values.database.database }}
  DB_PG_SCHEMA: {{ .Values.database.pg_schema }}
  DB_SSL: {{ .Values.database.ssl | quote }}
  {{- end }}

  {{- if .Values.ldap }}
  KONGA_AUTH_PROVIDER: {{ default "local" .Values.ldap.auth_provider }}
  KONGA_LDAP_HOST: {{ default "ldap://localhost:389" .Values.ldap.host }}
  KONGA_LDAP_BIND_DN: {{ .Values.ldap.bind_dn }}
  KONGA_LDAP_BIND_PASSWORD: {{ .Values.ldap.bind_pass }}
  KONGA_LDAP_USER_SEARCH_BASE: {{ default "ou=users,dc=com" .Values.ldap.user_search_base }}
  KONGA_LDAP_USER_SEARCH_FILTER: {{ default "(|(uid={{username}})(sAMAccountName={{username}}))" .Values.ldap.user_search_filter }}
  KONGA_LDAP_USER_ATTRS: {{ default "uid,uidNumber,givenName,sn,mail" .Values.ldap.user_attrs }}
  KONGA_LDAP_GROUP_SEARCH_BASE: {{ default "ou=groups,dc=com" .Values.ldap.group_search_base }}
  KONGA_LDAP_GROUP_SEARCH_FILTER: {{ default "(|(memberUid={{uid}})(memberUid={{uidNumber}})(sAMAccountName={{uid}}))" .Values.ldap.group_search_filter }}
  KONGA_LDAP_GROUP_ATTRS: {{ default "cn" .Values.ldap.group_attrs }}
  KONGA_ADMIN_GROUP_REG: {{ default "^(admin|konga)$" .Values.ldap.group_reg }}
  KONGA_LDAP_ATTR_USERNAME: {{ default "uid" .Values.ldap.attr_username }}
  KONGA_LDAP_ATTR_FIRSTNAME: {{ default "givenName" .Values.ldap.attr_firstname }}
  KONGA_LDAP_ATTR_LASTNAME: {{ default "sn" .Values.ldap.attr_lastname }}
  KONGA_LDAP_ATTR_EMAIL: {{ default "mail" .Values.ldap.attr_email }}
  {{- end }}
