apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "konga.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "konga.name" . }}
    helm.sh/chart: {{ include "konga.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
  {{- if len .Values.seed.kong_nodes }}
  kong_node.data: |-
    module.exports = {{ toPrettyJson .Values.seed.kong_nodes | indent 6 }}
  {{- end }}
  {{- if len .Values.seed.users }}
  userdb.data: |-
    module.exports = {{ toPrettyJson .Values.seed.users | indent 6 }}
  {{- end }}
