replicaCount: 1

image:
  repository: pantsel/konga
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

# https://github.com/pantsel/konga#environment-variables
config:
  port:
  node_env: development # needed to perform db migrations automatically on databases
  ssl:
    enabled: false
    key_path: ""
    crt_path: ""
  konga_hook_timeout:
  log_level: ""
  token_secret: ""

database:
  enabled: false
  adapter: postgres
  uri:
  host: localhost
  port: 5432
  ssl: false
  database: konga_database
  pg_schema: public
  credentials:
    from_secret: false # or secret name
    username: username # value or secret key
    password: password # value or secret key

seed:
  kong_nodes: []
#    - name: Kong Test Seed
#      type: default
#      kong_admin_url: http://kong:8001
#      health_checks: false
#      active: true
  users: []
#    - username: myadmin
#      email: myadmin@some.domain
#      firstName: Peter
#      lastName: Administrator
#      node_id: http://kong:8001
#      admin: true
#      active: true
#      password: somepassword

# https://github.com/pantsel/konga/blob/master/docs/LDAP.md
ldap: {}
#   auth_provider:
#   host:
#   bind_dn:
#   bind_pass:
#   user_search_base:
#   user_search_filter:
#   user_attrs:
#   group_search_base:
#   group_search_filter:
#   group_attrs:
#   group_reg:
#   attr_username:
#   attr_firstname:
#   attr_lastname:
#   attr_email:

ingress:
  enabled: false
  annotations: {}
  # kubernetes.io/tls-acme: "true"
  ingressClassName:
  hostname: chart-example.local
  path: /
  tlsSecretName: ""

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
#   memory: 128Mi

extraVolumes: []
extraVolumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
